branches:
  only:
    - travis
    - master
notifications:
  irc:
    channels:
      - "irc.mozilla.org#apps"
    on_success: change
    on_failure: change
language: node_js
node_js:
  - "0.11"
before_script:
  - "export SLIMERJSLAUNCHER=/usr/bin/firefox"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing Node Dependencies'"
  - "npm install"
  - "echo 'Building Brick'"
  - "make && make site"
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/v0.8/slimerjs-0.8.zip"
  - "unzip slimerjs-0.8.zip"
  - "sudo mv slimerjs-0.8 bin/slimerjs"
  - "echo 'Installing Casper'"
  - "git clone git://github.com/n1k0/casperjs.git casperjs"
  - "cd casperjs && git checkout 1.1-beta2 && cd .." # Use Homebrew's version of casper
script:
  - "./casperjs/bin/casperjs test --engine=slimerjs test"